# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f770fd541794820744598578f57e9902ca6cd5cbdd3b4698c0829224a12bf1e5a8a1f4c497dbabf567f220723ba6a5025c77ae9ff92bfa4191e9498167578daf

test:
  secret_key_base: c91bd78303533dbf6d53b9a6297b2589cc35281e61109e8d4e3ac221f61f1b0aed721f901a7c626abf3af49f83323bd7f64b0157835af95a6fc190bd53e9cb7d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
